### ISSUE TITLE
Please add "Copy pom.xml to your local directory" on readme 

### ISSUE THREAD

**Issue by JaeYJung** [googlegenomics/getting-started#2]
Maybe it's too obvious for maven users, but I'm not: spent 10 minutes to figure it out
(and it was downloaded as html file when I tried on my Mac).

**Comment by pgrosu** [comment]
Hi Jae-Yoon,

Thank you for trying this out and no steps are too obvious in my opinion :)  Please show us the web-link where you started and the steps you tried on your computer.

Thanks,
Paul

**Comment by JaeYJung** [comment]
It was my fault not to clone the project first: I tried to copy src file (only) and missed pom.xml file, which lead to "POM missing" error on maven assembly step. So I guess line-by-line followers like me would wish to see something like:

  1. Clone the project (assuming users are familiar with git commands)
  2. Install maven
  3. From cloned project directory (where pom.xml is located), run mvn assembly:single
  4. Run java -jar 

Thanks for your quick response,

Jae-Yoon

**Comment by pgrosu** [comment]
Great!  You can create a pull-request and update the document with the steps, so others can benefit.  I believe you will then need to sign a CLA so that Google will officially merge it.

Thanks,
Paul

**Comment by deflaux** [comment]
Thanks @JaeYJung !
